# create an .env file with 
# DATA_DIR=/srv/dev-disk-by-uuid-fc49e152-2bb3-4e7c-ad98-cb89f0cd6738/data/nextcloud
# when docke user default volumes (//var/lib/docker/volumes)
# looks like .env only works on services, not on volumes
#version: '2'
services:
  mariadb:
    image: yobasystems/alpine-mariadb
    restart: always
    volumes:
      - '${DATA_DIR}/nextcloud_db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
      - 443:443
    links:
      - mariadb
    volumes:
      - '${DATA_DIR}/nextcloud:/var/www/html'
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - PUID=1000
      - PGID=1000
